### ISSUE TITLE
Setup questions and issues

### ISSUE THREAD

**Issue by angusmcleod** [resonatecoop/user-api#1]
@merefield Thanks for the setup notes in the README, they helped me get it up and running locally. A few questions on that front.

1. I needed to install [protoc-gen-govalidators](github.com/mwitkow/go-proto-validators) locally to get ``make generate`` to work. Is that right?

2. I didn't entirely understand this in "Getting Started": "If you forked this repo, or cloned it into a different directory from the github structure...".

   - I didn't end up doing any of this and it still worked. Should I?
   - Is the reference to ``github.com/merefield`` correct?

3. I already had my go bin in my path. Is it worth mentioning this is necessary? i.e.

    ``export PATH=$PATH:$GOPATH/bin``

4. How are you handling https locally? I guess you have a live server already. Any thoughts on how this should be handled if you're not developing on a live server?

**Comment by merefield** [comment]
1. `I needed to install protoc-gen-govalidators locally to get make generate to work. Is that right?

That's correct, I've added instruction for that:

`Install the git submodule(s) with git submodule update --init from root directory of the cloned repo

2. those instuctions are updated

3. a little bit go general?  That should be the case anyway when working with go.
