### ISSUE TITLE
protoc-gen-go is missing in tools dependencies

### ISSUE THREAD

**Issue by ericburns** [resonatecoop/user-api#1]
Go Version: go1.12.9 darwin/amd64
OS: osx 10.14.5

1. Clone a fresh repo
2. Run `retool build`
3. Run `retool do protoc --proto_path=$GOPATH/src:. --twirp_out=. --go_out=. ./rpc/user/service.proto`

This error is thrown:
```
protoc-gen-go: program not found or is not executable
Please specify a program using absolute path or make sure the program is available in your PATH system variable
--go_out: protoc-gen-go: Plugin failed with status code 1.
retool: fatal err: failed on 'protoc --proto_path=/Users/eburns/go/src:. --twirp_out=. --go_out=. ./rpc/helloworld/service.proto': exit status 1
```

It looks like retool doesn't clean up the `/bin/` dir on sync or build, so when reproducing, you'd probably want to nuke that folder.

**Comment by blushi** [comment]
It seems like `protoc-gen-go` were not added to the project tools (on my side, it was working locally as I had it in my `$GOPATH/bin/`).
Please, pull the latest changes and retry after running `retool build` again.

**Comment by ericburns** [comment]
Works 😎 . Sorry I didn't submit a PR for this, but the versions I tried weren't generating the same code, so I knew I must have had the wrong version.
