### ISSUE TITLE
Stuck on `make generate` in Getting started directions

### ISSUE THREAD

**Issue by peterklingelhofer** [resonatecoop/user-api#23]
```sh
$ make generate
buf generate --path ./proto/user/common.proto
make: buf: No such file or directory
make: *** [generate] Error 1
```

**Comment by auggod** [comment]
Please try to install this https://docs.buf.build/installation

**Comment by auggod** [comment]
I think we should add a link to the grpc docs
https://grpc.io/docs/languages/go/quickstart/

If you have problems with plugins, make sure to update your `PATH`
`export PATH="$PATH:$(go env GOPATH)/bin"`

**Comment by peterklingelhofer** [comment]
Just to go over everything I did. I followed this [guide](https://www.digitalocean.com/community/tutorials/how-to-install-go-and-set-up-a-local-programming-environment-on-macos) to add `$PATH` to my env variables (I have zsh so I did `nano ~/.zshenv` and `. ~/.zshenv` instead of the `~/.bash_profile` reference they have in that guide. 

Then to get past this error:
```sh
❯ make generate                                     10:54:49
buf generate --path ./proto/user/common.proto
Failure: plugin govalidators: could not find protoc plugin for name govalidators
make: *** [generate] Error 1
```

I ran:
```sh
go install github.com/mwitkow/go-proto-validators/protoc-gen-govalidators
```
