### ISSUE TITLE
Unable to proceed past `Dev database setup` in Readme

### ISSUE THREAD

**Issue by peterklingelhofer** [resonatecoop/user-api#24]
> Create user and database as follows (as found in the local config file in `./conf.local.yaml`):
>
> username = "resonate_dev_user"
> 
> password = "password"
> 
> dbname = "resonate_dev"

What needs to be run to get into the database shell in order to create these? For ex, I know Postgres you typically can run `psql -U postgres`. It would be nice to have the Readme explicitly state this for new users so they don't have to go digging as to how to proceed past this step.

**Comment by peterklingelhofer** [comment]
```sh
❯ go run main.go runserver
2022/04/23 17:10:42 No env variable set for certificate directory
exit status 1
```

**Comment by peterklingelhofer** [comment]
```sh
sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/nginx-selfsigned.key -out /etc/ssl/certs/nginx-selfsigned.crt
Password:
Generating a 2048 bit RSA private key
.........................................+++
....+++
writing new private key to '/etc/ssl/private/nginx-selfsigned.key'
/etc/ssl/private/nginx-selfsigned.key: No such file or directory
4546195116:error:0EFFF06C:configuration file routines:CRYPTO_internal:no value:/System/Volumes/Data/SWE/macOS/BuildRoots/36806d33d2/Library/Caches/com.apple.xbs/Sources/libressl/libressl-56.60.3/libressl-2.8/crypto/conf/conf_lib.c:322:group=req name=default_bits
4546195116:error:02FFF002:system library:func(4095):No such file or directory:/System/Volumes/Data/SWE/macOS/BuildRoots/36806d33d2/Library/Caches/com.apple.xbs/Sources/libressl/libressl-56.60.3/libressl-2.8/crypto/bio/bss_file.c:255:fopen('/etc/ssl/private/nginx-selfsigned.key', 'w')
4546195116:error:20FFF002:BIO routines:CRYPTO_internal:system lib:/System/Volumes/Data/SWE/macOS/BuildRoots/36806d33d2/Library/Caches/com.apple.xbs/Sources/libressl/libressl-56.60.3/libressl-2.8/crypto/bio/bss_file.c:257:
```

**Comment by auggod** [comment]
I recommend using mkcert. https://github.com/FiloSottile/mkcert
Usage:
`mkcert 0.0.0.0 127.0.0.1 localhost ::1`

Now, given the command below:
`UACERT_DIR="/usr/local/etc/nginx/ssl" go run main.go runserver -env dev -dbdebug true`

User API will look for uaclient.key and uaclient.pem.

Rename mkcert generated key `...-key.pem` to uaclient.key.

User API is served at https://127.0.0.1:11000

**Comment by peterklingelhofer** [comment]
<img width="1357" alt="Screen Shot 2022-04-25 at 9 10 16 PM" src="https://user-images.githubusercontent.com/60944077/165205424-1bf67e95-c31a-48cc-b088-4be03fa69f01.png">

🎉 Looks like it's working now (excuse the screenshot, I had DarkReader on). Thank you for the `mkcert` recommendation, `openssl` seemed like it was a dead end with my current sys config.

Here are the steps I had to take from start to finish (mostly your directions above with a few additions):
```sh
mkcert -install
mkcert 0.0.0.0 127.0.0.1 localhost ::1
```

The certificate is in the directory you ran the above command from. Rename the key file (something like `./0.0.0.0+3-key.pem`) to `uaclient.key` and the certificate file (something like `./0.0.0.0+3.pem`) to `uaclient.pem`. Copy both of the renamed files to `/usr/local/etc/nginx/ssl` (if you don't have an `ssl` folder in your nginx directory, create one).

Serve the User API at https://127.0.0.1:11000 with this command:
```sh
UACERT_DIR="/usr/local/etc/nginx/ssl" go run main.go runserver -env dev -dbdebug true
```

**Comment by peterklingelhofer** [comment]
Trying psq now that server is runningl:
```sh
psql -U root
psql: error: connection to server on socket "/tmp/.s.PGSQL.5432" failed: No such file or directory
        Is the server running locally and accepting connections on that socket?
```

**Comment by peterklingelhofer** [comment]
Here's what I had to do to get past the above error...

Start the server:
```sh
pg_ctl -D /usr/local/var/postgres -l logfile start
```

For psql...
To get into the shell I ran:
```
psql
```

```sql
CREATE DATABASE resonate_dev;
CREATE USER resonate_dev_user WITH PASSWORD 'password';
\c resonate_dev;
CREATE EXTENSION hstore;
CREATE EXTENSION "uuid-ossp";
SELECT * FROM pg_extension;
```

Then I ran these loaders:
```sh
UACERT_DIR="/usr/local/etc/nginx/ssl" go run main.go db -env dev init
UACERT_DIR="/usr/local/etc/nginx/ssl" go run main.go db -env dev migrate                                                                                                     
UACERT_DIR="/usr/local/etc/nginx/ssl" go run main.go db -env dev load_default_fixtures
UACERT_DIR="/usr/local/etc/nginx/ssl" go run main.go db -env dev load_test_fixtures
```

I then repeated the last two above blocks replacing `dev` with `test`.
